platform :ios, '9.0'

target 'MovieX' do
  use_frameworks!
	pod 'SDWebImage'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Reusable'
	pod 'AlamofireObjectMapper'
	pod 'NSObject+Rx'
	pod 'MBProgressHUD'
	pod 'Cosmos' 
	pod 'SideMenu'
	pod 'MJRefresh'
	pod 'youtube-ios-player-helper'
	pod 'iCarousel'
	pod 'hpple'
	pod 'Then'
	pod 'MKProgress'
	pod 'RxGesture'
	pod 'Cards'

end
